#P2 Even Fibonacci numbers
#Each new term in the Fibonacci sequence is generated by adding the previous 
#two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed 
#four million, find the sum of the even-valued terms.


def even_fibonacci_numbers(n)
  lst=[1,2]
  i=1
  while lst[i]<=n
    lst[i+1]=lst[i-1]+lst[i]
    i+=1
  end
  return lst[0,lst.length-1].select{|x|x%2==0}.reduce(:+)  
end

p even_fibonacci_numbers(4000000)
